### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kotamori9** [kotamori9/chat-space#12]
# IPアドレス
18.221.175.57

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①ヘッダーの文字色を指定のものに変更しましょう！
[![Image from Gyazo](https://i.gyazo.com/91465d5f9090b29264eff286a00e592b.png)](https://gyazo.com/91465d5f9090b29264eff286a00e592b)

<見本>
[![Image from Gyazo](https://i.gyazo.com/3a391fd1837fadfcda80708524f7d108.png)](https://gyazo.com/3a391fd1837fadfcda80708524f7d108)

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
